Holybro-pixhawk-issue529
geerlingguy/raspberry-pi-pcie-devices pull request #532
Opened 2023-05-14 05:18 UTC by ExplodingLemur

Add Holybro Pixhawk CM4 baseboard per https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/529

2023-05-19 18:39 UTC, geerlingguy requested changes

2023-05-19 18:39 UTC, geerlingguy commented on Gemfile.lock
> +  x64-mingw-ucrt
This PR looks good except for I'm not sure what this would be useful for? Is this for something on Windows?

2023-09-09 03:31 UTC, closed without merging

2026-03-09 10:05 UTC, Syed-hyder-mahadi commented
I have quiery in Holybro Pixhawk 6x RPi CM4 Baseboard, how does this RPi CM4 will show the raspberry display output while using HDMI

2026-03-09 21:27 UTC, ExplodingLemur commented
> I have quiery in Holybro Pixhawk 6x RPi CM4 Baseboard, how does this RPi CM4 will show the raspberry display output while using HDMI

You should contact Holybro.